name: "CI Expo App"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: ğŸ“¥ Install dependencies
        run: npm ci

      - name: ğŸ¨ Format check
        run: npx prettier --check "**/*.{js,ts,jsx,tsx,json,md}" .

      - name: ğŸ§¹ Lint check
        run: npx eslint .

      - name: ğŸ©º Expo doctor
        run: npx expo-doctor
        env:
          EXPO_PUBLIC_URL_SERVEUR_API_DEV: ${{ secrets.EXPO_PUBLIC_URL_SERVEUR_API_DEV }}

      - name: âœ… Check splash image presence
        run: |
            if [ ! -f ./assets/images/splash-icon.png ]; then
              echo "âŒ Missing splash image at ./assets/images/splash-icon.png"
              exit 1
            else
              echo "âœ… Splash image found"
            fi
  
      - name: ğŸ§ª Prebuild dry-run (Android)
        run: npx expo prebuild --no-install --platform android
        env:
          EXPO_PUBLIC_URL_SERVEUR_API_DEV: ${{ secrets.EXPO_PUBLIC_URL_SERVEUR_API_DEV }}